/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ventanas;

import java.awt.Color;
import javax.swing.JOptionPane;
import objetos.Login;
import objetos.Usuario;

/**
 *
 * @author Claud
 */
public class VentanaLogin extends javax.swing.JFrame {
        //Instanciamos las clases usuario y log, para poder 
        //comprobar el usuario mediante la calse login.
        Usuario usuario = new Usuario();
        Login log = new Login();
    
    public VentanaLogin() {
        
         initComponents();
         //Llamada al metodo setLocation para que al iniciar el progama este aparezca en el centro
         this.setLocationRelativeTo(null);
         
         //cambiar el color del jframe
         this.getContentPane().setBackground(Color.decode("#005C89"));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txUsuario = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnInicioSesion = new javax.swing.JToggleButton();
        txPass = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(11, 27, 54));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("INICIO  SESION");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 100, -1, -1));

        txUsuario.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txUsuario.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel3.add(txUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 180, 200, 30));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Contraseña:");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 240, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Usuario:");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, -1, -1));

        btnInicioSesion.setBackground(new java.awt.Color(255, 153, 0));
        btnInicioSesion.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnInicioSesion.setText("Aceptar");
        btnInicioSesion.setBorder(null);
        btnInicioSesion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnInicioSesionMouseClicked(evt);
            }
        });
        jPanel3.add(btnInicioSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 330, 120, 40));

        txPass.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txPass.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel3.add(txPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 270, 200, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/fabrica60px.png"))); // NOI18N
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/ingeniero60px.png"))); // NOI18N
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/ropa60px.png"))); // NOI18N
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 20, -1, -1));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 340, 410));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnInicioSesionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnInicioSesionMouseClicked
       validar();
    }//GEN-LAST:event_btnInicioSesionMouseClicked

  // metodo par avalidar el usuario y contraseña
    public void validar(){
    
        String nombre = txUsuario.getText();
        String pass = txPass.getText();
        
        //En caso de que los campos esten varcios, avisamos con un dialog
        if(txUsuario.getText().isEmpty() || txPass.getText().isEmpty()){
        JOptionPane.showMessageDialog(this, "Tienes que introducir usuario y contraseña");
       
        }else{
        
            //Para poder comprobar los datos del usuario de la bd, llamamos al metodo valirdarUsuario de la 
            //clase login.
            usuario = log.varlidarUsuario(nombre, pass);
            
            
            //En caso de qe los datos del usuario existan en la bd, se accede a la ventana de inicio
            if(usuario.getNombre() != null && usuario.getPass() != null){
                Inicio ventanaInicio = new Inicio();
                ventanaInicio.setVisible(true);
                dispose();
             
            }else{
           
             //En caso de que algun datos sea incorrecto, se avisa con un dialog
                if(usuario.getNombre() ==null){
                    JOptionPane.showMessageDialog(this, "nombre error");}
                else if(usuario.getPass() ==null)
                    {
                    JOptionPane.showMessageDialog(this, "contraseña error");}
                    
                        txUsuario.requestFocus();
            }
        
        }
    }
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnInicioSesion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPasswordField txPass;
    private javax.swing.JTextField txUsuario;
    // End of variables declaration//GEN-END:variables
}
